import type { NewsItem } from "@/lib/types";
import { outletById } from "@/data/news";

/**
 * JSON-LD for search engines.
 *
 * Two jobs: tell crawlers what the publication is, and give the news pages an
 * explicit `dateModified` so freshness is stated rather than inferred. The
 * news list is marked up as a CollectionPage of links to other publishers —
 * which is what it honestly is. We do not claim authorship of their headlines.
 */

const BASE = "https://ukpoliticshub.com";

function Ld({ data }: { data: Record<string, unknown> }) {
  return (
    <script
      type="application/ld+json"
      // Content is generated by us, not user input; the replace guards against
      // a stray "</script>" inside any string breaking out of the tag.
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(data).replace(/</g, "\\u003c"),
      }}
    />
  );
}

/** Site-wide identity. Rendered once, in the root layout. */
export function SiteStructuredData() {
  return (
    <>
      <Ld
        data={{
          "@context": "https://schema.org",
          "@type": "Organization",
          "@id": `${BASE}/#organization`,
          name: "ukpoliticshub",
          url: BASE,
          logo: `${BASE}/icon`,
          description:
            "UK politics from both sides of the spectrum — polling, Channel crossings, threat levels, elections and news, every figure sourced.",
          publishingPrinciples: `${BASE}/how-we-work`,
        }}
      />
      <Ld
        data={{
          "@context": "https://schema.org",
          "@type": "WebSite",
          "@id": `${BASE}/#website`,
          name: "ukpoliticshub",
          url: BASE,
          publisher: { "@id": `${BASE}/#organization` },
          inLanguage: "en-GB",
        }}
      />
    </>
  );
}

/** The news index: what it is, when it last changed, and what is on it. */
export function NewsStructuredData({
  items,
  dateModified,
}: {
  items: NewsItem[];
  dateModified: string;
}) {
  return (
    <Ld
      data={{
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": `${BASE}/news#page`,
        url: `${BASE}/news`,
        name: "The news, by topic",
        description:
          "Today's British politics coverage from across the press, sorted by subject, with each masthead's left–right position shown alongside its stories.",
        isPartOf: { "@id": `${BASE}/#website` },
        dateModified,
        inLanguage: "en-GB",
        mainEntity: {
          "@type": "ItemList",
          numberOfItems: items.length,
          itemListElement: items.slice(0, 30).map((item, index) => ({
            "@type": "ListItem",
            position: index + 1,
            url: item.url,
            name: item.title,
            ...(outletById[item.outlet]
              ? { provider: { "@type": "Organization", name: outletById[item.outlet].name } }
              : {}),
          })),
        },
      }}
    />
  );
}
