import type { NewsItem } from "@/lib/types";
import { outletById } from "@/data/news";

/**
 * JSON-LD for search engines.
 *
 * Two jobs: tell crawlers what the publication is, and give the news pages an
 * explicit `dateModified` so freshness is stated rather than inferred. The
 * news list is marked up as a CollectionPage of links to other publishers —
 * which is what it honestly is. We do not claim authorship of their headlines.
 */

const BASE = "https://ukpoliticshub.com";

function Ld({ data }: { data: Record<string, unknown> }) {
  return (
    <script
      type="application/ld+json"
      // Content is generated by us, not user input; the replace guards against
      // a stray "</script>" inside any string breaking out of the tag.
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(data).replace(/</g, "\\u003c"),
      }}
    />
  );
}

/** Site-wide identity. Rendered once, in the root layout. */
export function SiteStructuredData() {
  return (
    <>
      <Ld
        data={{
          "@context": "https://schema.org",
          "@type": "Organization",
          "@id": `${BASE}/#organization`,
          name: "ukpoliticshub",
          url: BASE,
          logo: `${BASE}/icon`,
          description:
            "UK politics from both sides of the spectrum — polling, Channel crossings, threat levels, elections and news, every figure sourced.",
          publishingPrinciples: `${BASE}/how-we-work`,
        }}
      />
      <Ld
        data={{
          "@context": "https://schema.org",
          "@type": "WebSite",
          "@id": `${BASE}/#website`,
          name: "ukpoliticshub",
          url: BASE,
          publisher: { "@id": `${BASE}/#organization` },
          inLanguage: "en-GB",
        }}
      />
    </>
  );
}

/**
 * A constituency page: the seat as a place, and its MP as a person holding a
 * role. This is the markup behind "who is my MP" results, and the seat pages
 * had none of it.
 *
 * Only facts already on the page go in here. Nothing is asserted to a crawler
 * that a reader cannot also see and check.
 */
export function ConstituencyStructuredData({
  name,
  slug,
  nation,
  mp,
  places,
}: {
  name: string;
  slug: string;
  nation: string;
  mp: { name: string; party: string | null; memberId: number | null } | null;
  places: string[];
}) {
  const url = `${BASE}/constituencies/${slug}`;
  return (
    <Ld
      data={{
        "@context": "https://schema.org",
        "@type": "Place",
        "@id": `${url}#place`,
        url,
        name: `${name} constituency`,
        description: `${name} is a UK parliamentary constituency in ${nation}${
          places.length ? `, covering ${places.slice(0, 6).join(", ")}` : ""
        }.`,
        additionalType: "https://schema.org/AdministrativeArea",
        containedInPlace: { "@type": "Country", name: nation },
        isPartOf: { "@id": `${BASE}/#website` },
        ...(places.length
          ? { containsPlace: places.slice(0, 12).map((p) => ({ "@type": "Place", name: p })) }
          : {}),
        ...(mp
          ? {
              // The seat is represented by a person; the person holds the role.
              // Modelled this way round because the page is about the seat.
              subjectOf: {
                "@type": "Person",
                name: mp.name,
                jobTitle: `Member of Parliament for ${name}`,
                ...(mp.party ? { affiliation: { "@type": "Organization", name: mp.party } } : {}),
                ...(mp.memberId
                  ? { sameAs: `https://members.parliament.uk/member/${mp.memberId}` }
                  : {}),
              },
            }
          : {}),
      }}
    />
  );
}

/** The news index: what it is, when it last changed, and what is on it. */
export function NewsStructuredData({
  items,
  dateModified,
}: {
  items: NewsItem[];
  dateModified: string;
}) {
  return (
    <Ld
      data={{
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": `${BASE}/news#page`,
        url: `${BASE}/news`,
        name: "The news, by topic",
        description:
          "Today's British politics coverage from across the press, sorted by subject, with each masthead's left–right position shown alongside its stories.",
        isPartOf: { "@id": `${BASE}/#website` },
        dateModified,
        inLanguage: "en-GB",
        mainEntity: {
          "@type": "ItemList",
          numberOfItems: items.length,
          itemListElement: items.slice(0, 30).map((item, index) => ({
            "@type": "ListItem",
            position: index + 1,
            url: item.url,
            name: item.title,
            ...(outletById[item.outlet]
              ? { provider: { "@type": "Organization", name: outletById[item.outlet].name } }
              : {}),
          })),
        },
      }}
    />
  );
}
